{{- if and (index .Values "mongodb" "enabled") (index .Values "mongodb" "auth" "enabled") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "decisionbox-api.fullname" . }}-mongodb-uri
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "decisionbox-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  mongodb-uri: {{ include "decisionbox-api.mongodbURI" . | quote }}
{{- end }}
