{{- if .Values.serviceAccountName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "decisionbox-api.labels" . | nindent 4 }}
  {{- with .Values.serviceAccountAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.agentServiceAccount.name }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.agentServiceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "decisionbox-api.labels" . | nindent 4 }}
    app: decisionbox-agent
  {{- with .Values.agentServiceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
