# Grant license compliance policy for DecisionBox (AGPL-3.0)
# https://github.com/anchore/grant

require-license: false
require-known-license: false

allow:
  - MIT
  - Apache.*
  - BSD.*
  - ISC
  - 0BSD
  - Unlicense
  - CC0.*
  - CC-BY.*
  - MPL.*
  - LGPL.*
  - AGPL.*
  - GPL-3.*
  - PostgreSQL
  - Zlib
  - BlueOak.*
  - BSL-1.0
  - HPND
  - NCSA
  - OpenSSL
